"""empty message

Revision ID: d307f2d5fd90
Revises: f0fb386774ee
Create Date: 2025-07-22 11:25:34.187947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd307f2d5fd90'
down_revision = 'f0fb386774ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.alter_column('parameter_string',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.alter_column('parameter_string',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
