# Generated by Django 5.1.6 on 2025-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID товара в Stripe",
            ),
        ),
    ]
